(() => {
 const style=document.createElement('style');style.textContent=`.library-launch{margin:16px auto 0;padding:10px 20px;border:1px solid #b8d0f0;border-radius:7px;background:white;color:#1a2b4a;font:600 13px inherit;cursor:pointer}.library-dialog{width:min(1100px,94vw);max-width:1100px;height:88vh;max-height:92vh;border:0;border-radius:12px;padding:20px;background:white;color:#1a2b4a}.library-dialog::backdrop{background:#0f1923aa}.library-top,.library-tools,.library-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.library-top{justify-content:space-between}.library-top h2{font-size:20px;margin:0}.library-dialog button{padding:8px 12px;border:1px solid #ccd8e8;border-radius:6px;background:white;color:#1a2b4a;cursor:pointer}.library-dialog button.primary{background:#2e5fa3;color:white;border-color:#2e5fa3}.library-dialog button:disabled{opacity:.5;cursor:default}.library-caption{color:#5a6a80;font-size:12px;line-height:1.8}.library-tools{margin:18px 0}.library-dialog input,.library-dialog textarea,.library-dialog select{box-sizing:border-box;padding:10px;border:1px solid #ccd8e8;border-radius:6px;background:white;color:#1a2b4a;font:inherit;max-width:100%}.library-tools input{flex:1;min-width:160px}.library-empty{text-align:center;background:#f2f5f9;border:1px dashed #b8d0f0;border-radius:10px;padding:48px 20px}.library-empty strong{font-size:17px}.library-empty p{font-size:13px;color:#5a6a80}.library-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.library-item{border:1px solid #dde3ed;border-radius:8px;padding:16px;background:#f7f9fd}.library-item h3{margin:8px 0;font-size:15px}.library-item p{font-size:12px;line-height:1.7;color:#5a6a80}.library-item span{font-size:11px;color:#2e5fa3}.library-item button{margin-right:6px}.library-form{display:grid;gap:14px;margin:20px 0}.library-form label{display:grid;gap:6px;font-size:13px;font-weight:600}.library-form textarea{height:220px;font-weight:400;line-height:1.8}.library-form small{color:#5a6a80;font-weight:400;line-height:1.7}.library-body{white-space:pre-wrap;line-height:1.9;padding:20px;background:#f7f9fd;border:1px solid #dde3ed;border-radius:8px;margin:14px 0}.library-preview{width:100%;height:64vh;border:1px solid #dde3ed;border-radius:6px}.library-image{max-width:100%;display:block;margin:16px auto}.library-status{font-size:12px;line-height:1.7;color:#5a6a80}.library-status.error{color:#b42318}.library-file-note{font-size:12px;color:#5a6a80}.library-dialog [hidden]{display:none!important}@media(max-width:600px){.library-dialog{padding:14px}.library-top h2{font-size:18px}.library-preview{height:62vh}}`;
 document.head.append(style);
 const launch=document.createElement('button');launch.type='button';launch.className='library-launch';launch.textContent='社内マニュアル';document.querySelector('header').append(launch);
 const dialog=document.createElement('dialog');dialog.className='library-dialog';dialog.setAttribute('aria-labelledby','library-title');
 dialog.innerHTML=`<div class="library-top"><h2 id="library-title">社内マニュアル</h2><div class="library-actions"><button id="library-manage" type="button">管理</button><button id="library-close" type="button" aria-label="マニュアル格納庫を閉じる">×</button></div></div><p class="library-caption">社内マニュアルをここに格納し、この画面で読むことができます。</p><p id="library-status" class="library-status" role="status"></p><div id="library-catalog"><div class="library-tools"><input id="library-search" type="search" placeholder="マニュアルを検索" aria-label="マニュアルを検索"><select id="library-category" aria-label="分類"><option value="">すべての分類</option></select><button id="library-refresh" type="button">再読み込み</button><button id="library-new" type="button" hidden>ファイルを選択</button><input id="library-drop-file" type="file" accept=".pdf,.html,.htm,.png,.jpg,.jpeg,.webp,.docx,.pptx" hidden></div><div id="library-count" class="library-caption"></div><div id="library-list" class="library-list"></div><div id="library-empty" class="library-empty" hidden><strong>まだマニュアルは格納されていません</strong><p>PDF・HTMLをここにドロップすると自動保存します。ファイルを選択して追加することもできます。</p></div></div><div id="library-detail" hidden></div><form id="library-auth" class="library-form" hidden><label>管理用コード<input id="library-key" type="password" autocomplete="off" required></label><div class="library-actions"><button class="primary" type="submit">管理を開始</button><button id="library-auth-cancel" type="button">戻る</button></div><small>閲覧にはログインは不要です。追加・編集のときだけ管理用コードを使います。</small></form><form id="library-editor" class="library-form" hidden><label>マニュアル名<input id="library-name" maxlength="120" required><small>名前はいつでも変更でき、業務マップの表示にも反映します。</small></label><label hidden>分類<input id="library-folder" maxlength="80" placeholder="例：営業・人財対応・社内手続き"></label><label hidden>概要<input id="library-summary" maxlength="300"></label><label hidden>マニュアル本文<textarea id="library-content" maxlength="100000" placeholder="手順・注意点などをこの画面で直接作成できます。"></textarea></label><label>ファイルを格納・差し替え<input id="library-file" type="file" accept=".pdf,.html,.htm,.png,.jpg,.jpeg,.webp,.docx,.pptx"><small>PDF・HTML・画像はこの画面で表示できます。Word・PowerPointは原本を保存できます。1ファイル25MBまで。</small><small id="library-current-file"></small></label><div class="library-actions"><button id="library-save" class="primary" type="submit">格納する</button><button id="library-edit-cancel" type="button">キャンセル</button></div><small>入力・ファイル選択後に自動保存します。保存済みの内容は全員で共有され、以前の内容も履歴として残ります。</small></form>`;
 document.body.append(dialog);
 const el=id=>dialog.querySelector('#library-'+id);
 let manuals=[],canManage=false,editing=null,busy=false,activeScope='general',droppedFile=null,saveTimer=null,dirty=false,queued=false,draftOpen=false,previewAfterSave=false,activeReaderId=null,viewEpoch=0;
 function status(text,error=false){el('status').textContent=text;el('status').classList.toggle('error',error);}
 function view(name){for(const n of ['catalog','detail','auth','editor'])el(n).hidden=n!==name;dialog.scrollTop=0;}
 async function api(action,data){const response=await fetch('/api/manuals?action='+action,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});let result;try{result=await response.json();}catch{throw Error('保存先に接続できませんでした。');}if(!response.ok)throw Error(result.error||'操作に失敗しました。');return result;}
 function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
 function updateBadges(){document.querySelectorAll('.l2').forEach((section,index)=>{const items=manuals.filter(m=>m.scope==='business-'+(index+1));const count=items.length;const cls=count?'manual-ready':'manual-missing';const badge=section.querySelector('.l2-header>.manual-badge');if(badge){badge.classList.remove('manual-ready','manual-partial','manual-missing');badge.classList.add(cls);badge.textContent=count?'格納済み（'+count+'件）':'未格納';}const summary=section.querySelector('.manual-summary');if(summary){summary.classList.remove('manual-ready','manual-partial','manual-missing');summary.classList.add(cls);const name=summary.querySelector('strong');if(name)name.textContent=items.length?items.map(m=>m.title).join('・'):'マニュアル';}});}
 function render(){const q=el('search').value.trim().toLowerCase(),category=el('category').value;const scoped=manuals.filter(m=>activeScope==='general'||m.scope===activeScope);const shown=scoped.filter(m=>(!category||m.category===category)&&(!q||(m.title+' '+m.category+' '+m.summary).toLowerCase().includes(q)));el('list').replaceChildren();el('count').textContent=scoped.length+'件のマニュアル'+(q||category?' ／ 表示 '+shown.length+'件':'');el('empty').hidden=shown.length>0;if(!shown.length){el('empty').querySelector('strong').textContent=scoped.length?'該当するマニュアルはありません':'まだマニュアルは格納されていません';el('empty').querySelector('p').textContent=scoped.length?'検索条件を変えてください。':'PDF・HTMLをここにドロップすると自動保存します。ファイルを選択して追加することもできます。';}
  for(const m of shown){const card=node('article',undefined,'library-item');card.append(node('h3',m.title),node('p','更新：'+new Date(m.updatedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})));const read=node('button','読む');read.onclick=()=>readManual(m.id);card.append(read);if(canManage){const edit=node('button','編集・差し替え');edit.onclick=()=>editManual(m.id);card.append(edit);}el('list').append(card);}
 }
 async function load(quiet=false,autoOpen=false){const epoch=viewEpoch,scope=activeScope;if(!quiet)status('読み込み中…');try{const s=await api('status');if(epoch!==viewEpoch)return;canManage=s.canManage;el('manage').hidden=s.publicWrite;el('manage').textContent=canManage?'管理を終了':'管理';el('new').hidden=false;el('save').disabled=!canManage;if(!s.ready){status('マニュアルの保存先を準備中です。',true);return;}const result=await api('list');if(epoch!==viewEpoch)return;manuals=result.manuals;updateBadges();const selected=el('category').value;el('category').replaceChildren(new Option('すべての分類',''),...[...new Set(manuals.map(m=>m.category))].sort().map(c=>new Option(c,c)));el('category').value=selected;render();status('');if(autoOpen&&dialog.open&&scope===activeScope){const items=manuals.filter(m=>scope==='general'||m.scope===scope);if(items.length)await readManual(items[0].id);}}catch(e){status(e.message,true);}}
 async function readManual(id){const epoch=viewEpoch;status('読み込み中…');try{const m=await api('read&id='+encodeURIComponent(id));if(epoch!==viewEpoch||!dialog.open)return;activeReaderId=m.id;const content=el('detail');content.replaceChildren();const tools=node('div',undefined,'library-actions');const items=manuals.filter(item=>activeScope==='general'||item.scope===activeScope);if(items.length>1){const select=node('select');select.setAttribute('aria-label','表示するマニュアル');for(const item of items)select.append(new Option(item.title,item.id));select.value=m.id;select.onchange=()=>readManual(select.value);tools.append(select);}if(canManage){const rename=node('button','名前変更・差し替え');rename.onclick=()=>editManual(m.id);const replace=node('button','ファイルを差し替え');replace.onclick=()=>el('drop-file').click();tools.append(rename,replace);}content.append(tools,node('h3',m.title));if(m.content)content.append(node('div',m.content,'library-body'));if(m.file){const url='/api/manuals?action=asset&id='+encodeURIComponent(m.id)+'&v='+encodeURIComponent(m.version);content.append(node('p',m.file.name,'library-file-note'));if(m.file.type==='application/pdf'){const frame=node('iframe',undefined,'library-preview');frame.title=m.title;frame.src='manual-reader.html?id='+encodeURIComponent(m.id)+'&v='+encodeURIComponent(m.version);content.append(frame);}else if(m.file.type==='text/html'){const frame=node('iframe',undefined,'library-preview');frame.title=m.title;frame.setAttribute('sandbox','');frame.src=url;content.append(frame);}else if(m.file.type.startsWith('image/')){const image=node('img',undefined,'library-image');image.src=url;image.alt=m.title;content.append(image);}else{const a=node('a','原本ファイルを保存');a.href=url;a.download=m.file.name;content.append(a,node('p','この原本の画面内表示には、PDF版を格納してください。','library-file-note'));}}view('detail');status('');}catch(e){status(e.message,true);}}
 async function editManual(id){const epoch=viewEpoch;try{clearTimeout(saveTimer);dirty=false;queued=false;draftOpen=true;const doc=id?await api('read&id='+encodeURIComponent(id)):null;if(epoch!==viewEpoch||!dialog.open)return;editing=doc;droppedFile=null;for(const [field,key] of [['name','title'],['folder','category'],['summary','summary'],['content','content']])el(field).value=editing?.[key]||'';el('file').value='';el('current-file').textContent=editing?.file?'格納済み：'+editing.file.name+'（ファイルを選ばなければ維持します）':'';el('save').textContent='今すぐ保存';view('editor');status(canManage?'入力後に自動保存します。':'格納するには「管理」から管理用コードを入力してください。');}catch(e){status(e.message,true);}}
 function openReceiver(scope,title){viewEpoch++;previewAfterSave=false;draftOpen=false;activeReaderId=null;activeScope=scope;for(const id of ['search','category','refresh'])el(id).hidden=scope!=='general';el('title').textContent=title;el('search').value='';el('category').value='';manuals=[];render();view('catalog');if(!dialog.open)dialog.showModal();load(false,true);}launch.onclick=()=>openReceiver('general','社内マニュアル');window.openManual=function(n){const section=document.querySelectorAll('.l2')[Number(n)-1];const title=section?.querySelector('.l2-header')?.textContent.replace(/対応資料あり|補足が必要|マニュアル未整備（要確認）|格納済み（\d+件）|未格納|[▶▼]/g,'').trim()||'業務 '+n;openReceiver('business-'+n,title+'｜マニュアル');};document.querySelectorAll('.manual-summary').forEach(button=>{button.setAttribute('aria-label','マニュアルを格納・閲覧');const name=button.querySelector('strong');if(name)name.textContent='マニュアル';for(const child of [...button.childNodes])if(child.nodeType===Node.TEXT_NODE)child.textContent='';const hint=button.querySelector('.manual-detail-hint');if(hint)hint.textContent='格納・閲覧';});async function leaveEditor(close=false){if(busy){status('保存中です。完了までお待ちください。');return;}clearTimeout(saveTimer);if(dirty&&canManage&&!(await saveNow()))return;draftOpen=false;if(close){viewEpoch++;dialog.close();}else view('catalog');}
 el('close').onclick=()=>leaveEditor(true);dialog.addEventListener('cancel',event=>{event.preventDefault();leaveEditor(true);});el('refresh').onclick=load;el('search').oninput=render;el('category').onchange=render;el('new').onclick=()=>el('drop-file').click();el('drop-file').onchange=()=>{const file=el('drop-file').files[0];if(file)acceptFile(file);el('drop-file').value='';};el('auth-cancel').onclick=()=>view(draftOpen?'editor':'catalog');el('edit-cancel').textContent='一覧へ戻る';el('edit-cancel').onclick=()=>leaveEditor();
 el('manage').onclick=async()=>{if(busy)return;if(canManage){if(dirty&&!(await saveNow()))return;await api('logout',{});await load();view('catalog');draftOpen=false;}else{view('auth');el('key').focus();}};
 el('auth').onsubmit=async event=>{event.preventDefault();try{await api('login',{key:el('key').value});el('key').value='';await load();view(draftOpen?'editor':'catalog');if(draftOpen&&dirty)scheduleSave(0);}catch(e){status(e.message,true);}};
 function scheduleSave(delay=900){dirty=true;clearTimeout(saveTimer);if(!canManage){status('まだ保存されていません。「管理」から管理用コードを入力すると自動保存できます。');return;}status('未保存の変更があります。自動保存を待っています…');saveTimer=setTimeout(saveNow,delay);}
 for(const field of ['name','folder','summary','content'])el(field).addEventListener('input',()=>scheduleSave());
 el('file').onchange=()=>{previewAfterSave=true;droppedFile=null;const file=el('file').files[0];if(file&&!el('name').value.trim())el('name').value=file.name.replace(/\.[^.]+$/,'');scheduleSave(0);};
 async function saveNow(){clearTimeout(saveTimer);if(busy){queued=true;return false;}if(!dirty)return true;if(!canManage){status('自動保存には管理用コードが必要です。',true);return false;}
 const selected=droppedFile||el('file').files[0],title=el('name').value.trim(),content=el('content').value;
 if(!title||(!content.trim()&&!selected&&!editing?.file)){status('タイトルと、本文またはファイルを入力すると自動保存します。');return false;}
 const payload={id:editing?.id||crypto.randomUUID(),baseVersion:editing?.version||null,scope:editing?.scope||activeScope,title,category:el('folder').value,summary:el('summary').value,content,file:null};
 dirty=false;busy=true;queued=false;el('save').disabled=true;el('edit-cancel').disabled=true;let succeeded=false;
 try{if(selected){if(!selected.size||selected.size>25*1024*1024)throw Error('ファイルは空でない25MB以内のものを選んでください。');const types={pdf:'application/pdf',html:'text/html',htm:'text/html',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'},type=types[selected.name.split('.').pop().toLowerCase()];if(!type)throw Error('対応するファイル形式で選んでください。');const uploadId=crypto.randomUUID(),size=2*1024*1024,parts=Math.ceil(selected.size/size);for(let i=0;i<parts;i++){status('自動保存中… '+(i+1)+' / '+parts);const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(selected.slice(i*size,(i+1)*size));});await api('part',{id:payload.id,uploadId,index:i,data});}payload.file={name:selected.name,type,size:selected.size,parts,uploadId};}
 status('自動保存中…');const result=await api('save',payload);editing=result.manual;const current=droppedFile||el('file').files[0];if(current===selected){droppedFile=null;el('file').value='';}el('current-file').textContent=editing.file?'格納済み：'+editing.file.name:'';manuals=(await api('list')).manuals;updateBadges();render();status('自動保存済み：'+new Date().toLocaleTimeString('ja-JP'));succeeded=true;
 }catch(error){dirty=true;status('保存できませんでした。変更はこの画面に残っています。'+error.message,true);}
 finally{busy=false;el('save').disabled=!canManage;el('edit-cancel').disabled=false;if(succeeded&&(dirty||queued))scheduleSave();else if(succeeded&&previewAfterSave){previewAfterSave=false;draftOpen=false;await readManual(editing.id);}}return succeeded;}
 el('editor').onsubmit=event=>{event.preventDefault();dirty=true;saveNow();};window.addEventListener('beforeunload',event=>{if(dirty||busy){event.preventDefault();event.returnValue='';}});
 async function acceptFile(file){if(busy){status('保存が完了してから次のファイルを追加してください。');return;}if(!/\.(pdf|html?|png|jpe?g|webp|docx|pptx)$/i.test(file.name)||!file.size||file.size>25*1024*1024){status('PDF・HTMLなど、空でない25MB以内の対応ファイルを選んでください。',true);return;}const scoped=manuals.filter(m=>m.scope===activeScope);const replaceId=scoped.some(m=>m.id===activeReaderId)?activeReaderId:(activeScope!=='general'&&scoped.length===1?scoped[0].id:null);const epoch=viewEpoch;await editManual(replaceId);if(epoch!==viewEpoch||!dialog.open)return;droppedFile=file;el('name').value=replaceId?editing.title:file.name.replace(/\.[^.]+$/,'');el('current-file').textContent='選択済み：'+file.name;previewAfterSave=true;scheduleSave(0);}
 const dropZone=dialog;dropZone.addEventListener('dragover',event=>{event.preventDefault();el('empty').style.borderColor='#2e5fa3';});dropZone.addEventListener('dragleave',()=>{el('empty').style.borderColor='';});dropZone.addEventListener('drop',async event=>{event.preventDefault();el('empty').style.borderColor='';const files=[...event.dataTransfer.files];if(files.length!==1){status('ファイルは1件ずつドロップしてください。',true);return;}await acceptFile(files[0]);});
 function refreshVisibleCatalog(){if(dialog.open&&!el('catalog').hidden&&!busy&&!dirty&&document.visibilityState==='visible')load(true);}setInterval(refreshVisibleCatalog,30000);document.addEventListener('visibilitychange',refreshVisibleCatalog);
 updateBadges();load();
})();
