(() => {
 const style=document.createElement('style');style.textContent=`.library-launch{margin:16px auto 0;padding:10px 20px;border:1px solid #b8d0f0;border-radius:7px;background:white;color:#1a2b4a;font:600 13px inherit;cursor:pointer}.library-dialog{width:min(1100px,94vw);max-width:1100px;height:88vh;max-height:92vh;border:0;border-radius:12px;padding:20px;background:white;color:#1a2b4a}.library-dialog::backdrop{background:#0f1923aa}.library-top,.library-tools,.library-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.library-top{justify-content:space-between}.library-top h2{font-size:20px;margin:0}.library-dialog button{padding:8px 12px;border:1px solid #ccd8e8;border-radius:6px;background:white;color:#1a2b4a;cursor:pointer}.library-dialog button.primary{background:#2e5fa3;color:white;border-color:#2e5fa3}.library-dialog button:disabled{opacity:.5;cursor:default}.library-caption{color:#5a6a80;font-size:12px;line-height:1.8}.library-tools{margin:18px 0}.library-dialog input,.library-dialog textarea,.library-dialog select{box-sizing:border-box;padding:10px;border:1px solid #ccd8e8;border-radius:6px;background:white;color:#1a2b4a;font:inherit;max-width:100%}.library-tools input{flex:1;min-width:160px}.library-empty{text-align:center;background:#f2f5f9;border:1px dashed #b8d0f0;border-radius:10px;padding:48px 20px}.library-empty strong{font-size:17px}.library-empty p{font-size:13px;color:#5a6a80}.library-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.library-item{border:1px solid #dde3ed;border-radius:8px;padding:16px;background:#f7f9fd}.library-item h3{margin:8px 0;font-size:15px}.library-item p{font-size:12px;line-height:1.7;color:#5a6a80}.library-item span{font-size:11px;color:#2e5fa3}.library-item button{margin-right:6px}.library-form{display:grid;gap:14px;margin:20px 0}.library-form label{display:grid;gap:6px;font-size:13px;font-weight:600}.library-form textarea{height:220px;font-weight:400;line-height:1.8}.library-form small{color:#5a6a80;font-weight:400;line-height:1.7}.library-body{white-space:pre-wrap;line-height:1.9;padding:20px;background:#f7f9fd;border:1px solid #dde3ed;border-radius:8px;margin:14px 0}.library-preview{width:100%;height:64vh;border:1px solid #dde3ed;border-radius:6px}.library-image{max-width:100%;display:block;margin:16px auto}.library-status{font-size:12px;line-height:1.7;color:#5a6a80}.library-status.error{color:#b42318}.library-file-note{font-size:12px;color:#5a6a80}.library-dialog [hidden]{display:none!important}@media(max-width:600px){.library-dialog{padding:14px}.library-top h2{font-size:18px}.library-preview{height:62vh}}`;
 document.head.append(style);
 const launch=document.createElement('button');launch.type='button';launch.className='library-launch';launch.textContent='社内マニュアル';document.querySelector('header').append(launch);
 const dialog=document.createElement('dialog');dialog.className='library-dialog';dialog.setAttribute('aria-labelledby','library-title');
 dialog.innerHTML=`<div class="library-top"><h2 id="library-title">社内マニュアル</h2><div class="library-actions"><button id="library-manage" type="button">管理</button><button id="library-close" type="button" aria-label="マニュアル格納庫を閉じる">×</button></div></div><p class="library-caption">社内マニュアルをここに格納し、この画面で読むことができます。</p><p id="library-status" class="library-status" role="status"></p><div id="library-catalog"><div class="library-tools"><input id="library-search" type="search" placeholder="マニュアルを検索" aria-label="マニュアルを検索"><select id="library-category" aria-label="分類"><option value="">すべての分類</option></select><button id="library-refresh" type="button">再読み込み</button><button id="library-new" class="primary" type="button" hidden>マニュアルを追加</button></div><div id="library-count" class="library-caption"></div><div id="library-list" class="library-list"></div><div id="library-empty" class="library-empty" hidden><strong>まだマニュアルは格納されていません</strong><p>受け皿は準備できています。マニュアルは今後ここに追加できます。</p></div></div><div id="library-detail" hidden></div><form id="library-auth" class="library-form" hidden><label>管理用コード<input id="library-key" type="password" autocomplete="off" required></label><div class="library-actions"><button class="primary" type="submit">管理を開始</button><button id="library-auth-cancel" type="button">戻る</button></div><small>閲覧にはログインは不要です。追加・編集のときだけ管理用コードを使います。</small></form><form id="library-editor" class="library-form" hidden><label>タイトル<input id="library-name" maxlength="120" required></label><label>分類<input id="library-folder" maxlength="80" placeholder="例：営業・人財対応・社内手続き"></label><label>概要<input id="library-summary" maxlength="300"></label><label>マニュアル本文<textarea id="library-content" maxlength="100000" placeholder="手順・注意点などをこの画面で直接作成できます。"></textarea></label><label>ファイルを格納・差し替え<input id="library-file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.docx,.pptx"><small>PDF・画像はこの画面で表示できます。Word・PowerPointは原本を保存できます。1ファイル25MBまで。</small><small id="library-current-file"></small></label><div class="library-actions"><button id="library-save" class="primary" type="submit">格納する</button><button id="library-edit-cancel" type="button">キャンセル</button></div><small>差し替えても、以前の内容は履歴として保存します。</small></form>`;
 document.body.append(dialog);
 const el=id=>dialog.querySelector('#library-'+id);
 let manuals=[],canManage=false,editing=null,busy=false;
 function status(text,error=false){el('status').textContent=text;el('status').classList.toggle('error',error);}
 function view(name){for(const n of ['catalog','detail','auth','editor'])el(n).hidden=n!==name;dialog.scrollTop=0;}
 async function api(action,data){const response=await fetch('/api/manuals?action='+action,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});let result;try{result=await response.json();}catch{throw Error('保存先に接続できませんでした。');}if(!response.ok)throw Error(result.error||'操作に失敗しました。');return result;}
 function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
 function render(){const q=el('search').value.trim().toLowerCase(),category=el('category').value;const shown=manuals.filter(m=>(!category||m.category===category)&&(!q||(m.title+' '+m.category+' '+m.summary).toLowerCase().includes(q)));el('list').replaceChildren();el('count').textContent=manuals.length+'件のマニュアル'+(q||category?' ／ 表示 '+shown.length+'件':'');el('empty').hidden=shown.length>0;if(!shown.length){el('empty').querySelector('strong').textContent=manuals.length?'該当するマニュアルはありません':'まだマニュアルは格納されていません';el('empty').querySelector('p').textContent=manuals.length?'検索条件を変えてください。':'受け皿は準備できています。マニュアルは今後ここに追加できます。';}
  for(const m of shown){const card=node('article',undefined,'library-item');card.append(node('span',m.category),node('h3',m.title),node('p',m.summary||'概要は未記入です。'),node('p','更新：'+new Date(m.updatedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})));const read=node('button','読む');read.onclick=()=>readManual(m.id);card.append(read);if(canManage){const edit=node('button','編集・差し替え');edit.onclick=()=>editManual(m.id);card.append(edit);}el('list').append(card);}
 }
 async function load(){status('読み込み中…');try{const s=await api('status');canManage=s.canManage;el('manage').textContent=canManage?'管理を終了':'管理';el('new').hidden=!canManage;if(!s.ready){status('マニュアルの保存先を準備中です。',true);return;}manuals=(await api('list')).manuals;const selected=el('category').value;el('category').replaceChildren(new Option('すべての分類',''),...[...new Set(manuals.map(m=>m.category))].sort().map(c=>new Option(c,c)));el('category').value=selected;render();status(canManage?'管理モード：追加・編集できます。':'');}catch(e){status(e.message,true);}}
 async function readManual(id){status('読み込み中…');try{const m=await api('read&id='+encodeURIComponent(id));const content=el('detail');content.replaceChildren();const back=node('button','一覧へ戻る');back.onclick=()=>view('catalog');content.append(back,node('h3',m.title),node('p',m.category,'library-caption'));if(m.content)content.append(node('div',m.content,'library-body'));if(m.file){const url='/api/manuals?action=asset&id='+encodeURIComponent(m.id)+'&v='+encodeURIComponent(m.version);content.append(node('p',m.file.name,'library-file-note'));if(m.file.type==='application/pdf'){const frame=node('iframe',undefined,'library-preview');frame.title=m.title;frame.src='manual-reader.html?id='+encodeURIComponent(m.id)+'&v='+encodeURIComponent(m.version);content.append(frame);}else if(m.file.type.startsWith('image/')){const image=node('img',undefined,'library-image');image.src=url;image.alt=m.title;content.append(image);}else{const a=node('a','原本ファイルを保存');a.href=url;a.download=m.file.name;content.append(a,node('p','この原本の画面内表示には、PDF版を格納してください。','library-file-note'));}}view('detail');status('');}catch(e){status(e.message,true);}}
 async function editManual(id){try{editing=id?await api('read&id='+encodeURIComponent(id)):null;for(const [field,key] of [['name','title'],['folder','category'],['summary','summary'],['content','content']])el(field).value=editing?.[key]||'';el('file').value='';el('current-file').textContent=editing?.file?'格納済み：'+editing.file.name+'（ファイルを選ばなければ維持します）':'';el('save').textContent=editing?'変更を保存':'格納する';view('editor');status('');}catch(e){status(e.message,true);}}
 launch.onclick=()=>{view('catalog');dialog.showModal();load();};el('close').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});el('refresh').onclick=load;el('search').oninput=render;el('category').onchange=render;el('new').onclick=()=>editManual();el('auth-cancel').onclick=()=>view('catalog');el('edit-cancel').onclick=()=>view('catalog');
 el('manage').onclick=async()=>{if(canManage){await api('logout',{});await load();view('catalog');}else{view('auth');el('key').focus();}};
 el('auth').onsubmit=async event=>{event.preventDefault();try{await api('login',{key:el('key').value});el('key').value='';await load();view('catalog');}catch(e){status(e.message,true);}};
 el('editor').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;el('save').disabled=true;el('edit-cancel').disabled=true;try{const id=editing?.id||crypto.randomUUID();let file=null;const selected=el('file').files[0];if(selected){if(selected.size>25*1024*1024)throw Error('ファイルは25MB以内で選んでください。');const uploadId=crypto.randomUUID(),size=2*1024*1024,parts=Math.ceil(selected.size/size);const types={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'};const type=types[selected.name.split('.').pop().toLowerCase()];if(!type)throw Error('対応するファイル形式で選んでください。');for(let i=0;i<parts;i++){status('ファイルを格納中… '+(i+1)+' / '+parts);const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(selected.slice(i*size,(i+1)*size));});await api('part',{id,uploadId,index:i,data});}file={name:selected.name,type,size:selected.size,parts,uploadId};}status('保存中…');await api('save',{id,baseVersion:editing?.version||null,title:el('name').value,category:el('folder').value,summary:el('summary').value,content:el('content').value,file});await load();view('catalog');status('マニュアルを格納しました。');}catch(e){status(e.message,true);}finally{busy=false;el('save').disabled=false;el('edit-cancel').disabled=false;}};
})();
